adsorbates:
  - !import ["ar.yaml"]
hosts:
  - cif_file: v0.6/WPA_kups_widom/cifs_p1/MFI_P1.cif
    pressure: 100000.0
    temperature: 298.15
    init_adsorbates: [0]
    cell_replication: 2
lj: !import ["lj_6c_withSi.yaml"]
ewald:
  real_cutoff: 12.0
  precision: 1.e-6
run:
  out_file: /tmp/kups_6c_withSi.h5
  num_cycles: 50
  num_warmup_cycles: 10
  num_displacements_per_cycle: 20
  num_widom_per_cycle: 500
  translation_prob: 0.333
  rotation_prob: 0.333
  reinsertion_prob: 0.333
  seed: 0
max_num_adsorbates: 200
