"""External-samples backend — ingest pre-computed Widom samples from any engine.

This backend takes an ``.npz`` file generated by the operator's choice of
serious calculator (RASPA3, LAMMPS, OpenMM, kUPS, custom MD, ML-FF, …) and
feeds the samples directly into the atlas pipeline without re-running
insertion. The backend is **strict-schema**: every NPZ must arrive paired
with an :class:`~widom_atlas.backends.schema.ExternalSampleManifest`
JSON sidecar declaring units + force-field provenance + redistribution
status.

Two layouts are supported:

1. **Manifest sidecar** (preferred):
   ``samples.npz`` + ``samples.npz.manifest.json`` (or explicit
   ``--external-manifest`` path). The JSON is parsed into
   :class:`ExternalSampleManifest` and energies are converted from the
   declared unit to eV.

2. **Legacy embedded mode** (kept for backward compatibility): the .npz
   carries ``metadata_json`` with ``gas`` and ``structure_id``; energies
   are assumed to be in **eV** (the original convention) and a
   ``manifest_inferred = true`` warning is appended. New code should NOT
   rely on this — use the strict schema.

Per ``implementation-verdict-continuation.txt`` §"Implement external sample
schema": the schema is the contract, units are mandatory, missing units
fail loudly.
"""

from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

from .base import BackendOutput
from .schema import ExternalSampleManifest, manifest_summary
from .units import to_eV

_LOGGER = logging.getLogger(__name__)


def _sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def _default_manifest_path(samples_path: Path) -> Path:
    return samples_path.with_suffix(samples_path.suffix + ".manifest.json")


@dataclass(frozen=True)
class ExternalSamplesBackend:
    """Backend that ingests an external NPZ of Widom samples.

    The ``manifest_path`` argument may be ``None``; when ``None`` the
    backend looks for ``<samples_path>.manifest.json`` next to the npz,
    and if that is missing falls back to legacy embedded-metadata mode
    (with a warning).
    """

    samples_path: Path
    manifest_path: Path | None = None
    name: str = "external_samples"

    def generate(
        self,
        *,
        structure: Any,
        gas: str,
        temperature_K: float,
        n_samples: int,
        seed: int,
        material_id: str,
        material_source: str,
        extra_metadata: dict[str, Any] | None = None,
    ) -> BackendOutput:
        from widom_atlas.io.npz import from_npz

        path = Path(self.samples_path)
        if not path.exists():
            raise FileNotFoundError(f"external_samples backend: {path} not found")
        sha_samples = _sha256_of(path)

        manifest_path = Path(self.manifest_path) if self.manifest_path else _default_manifest_path(path)
        manifest_loaded: ExternalSampleManifest | None = None
        manifest_warnings: list[str] = []
        if manifest_path.exists():
            raw = json.loads(manifest_path.read_text(encoding="utf-8"))
            manifest_loaded = ExternalSampleManifest.model_validate(raw)
        else:
            manifest_warnings.append(
                "manifest_inferred: no <samples>.manifest.json sidecar found; "
                "falling back to legacy embedded metadata. Energies are assumed to be in eV. "
                "New runs should ship a strict ExternalSampleManifest sidecar — "
                "see widom_atlas.backends.schema."
            )

        atlas_input = from_npz(path, structure=structure)
        if atlas_input.gas != gas:
            raise ValueError(
                f"external_samples gas={atlas_input.gas!r} does not match requested gas={gas!r}"
            )
        if abs(atlas_input.temperature_K - float(temperature_K)) > 1e-6:
            raise ValueError(
                f"external_samples temperature_K={atlas_input.temperature_K} does not match requested {temperature_K}"
            )
        n_actual = atlas_input.samples.energies_eV.shape[0]
        if n_actual < n_samples:
            raise ValueError(
                f"external_samples contain {n_actual} insertions but {n_samples} requested"
            )

        # Apply unit conversion when manifest declares energies in something other than eV.
        # The .npz schema stores `energies_eV` as a literal field name, but the producer may
        # have written non-eV values; manifest is the source of truth.
        if manifest_loaded is not None and manifest_loaded.energy_unit != "eV":
            converted = to_eV(np.asarray(atlas_input.samples.energies_eV), manifest_loaded.energy_unit)
            from widom_atlas.io.from_arrays import from_arrays

            atlas_input = from_arrays(
                structure=structure,
                positions_cart=atlas_input.samples.positions_cart,
                positions_frac=atlas_input.samples.positions_frac,
                energies_eV=converted,
                accessible=atlas_input.samples.accessible,
                temperature_K=float(temperature_K),
                gas=gas,
                metadata=dict(atlas_input.metadata),
            )

        metadata = dict(atlas_input.metadata) if atlas_input.metadata else {}
        metadata.update(
            {
                "benchmark_material_id": material_id,
                "benchmark_source": material_source,
                "backend": self.name,
                "backend_category": "external_samples",
                "external_samples_path": str(path),
                "external_samples_sha256": sha_samples,
                "samples_origin": "external_samples",
                "random_seed": int(seed),
                "n_insertions": int(n_samples),
            }
        )
        if manifest_loaded is not None:
            metadata["external_sample_manifest"] = manifest_summary(manifest_loaded)
            metadata["warnings"] = list(manifest_loaded.warnings) + manifest_warnings
        else:
            metadata["external_sample_manifest"] = None
            metadata["warnings"] = manifest_warnings
        if extra_metadata:
            metadata.update(extra_metadata)
        atlas_input = atlas_input.model_copy(update={"metadata": metadata})

        provenance: dict[str, Any] = {
            "external_samples_path": str(path),
            "external_samples_sha256": sha_samples,
            "n_samples_in_file": str(n_actual),
            "manifest_path": str(manifest_path) if manifest_loaded is not None else None,
            "manifest_present": str(manifest_loaded is not None),
            "ingest_only_no_calculator_run": "true",
            "warnings": metadata.get("warnings", []),
        }
        if manifest_loaded is not None:
            provenance["energy_unit_declared"] = manifest_loaded.energy_unit
            provenance["redistribution_status"] = manifest_loaded.redistribution_status
            provenance["force_field"] = manifest_loaded.force_field.model_dump()
            provenance["citations"] = [c.model_dump() for c in manifest_loaded.citations]
        return BackendOutput(
            atlas_input=atlas_input,
            backend_label=(
                f"external_samples ({path.name}, sha256={sha_samples[:12]}…"
                + (f", manifest={manifest_path.name}" if manifest_loaded else ", manifest=inferred")
                + ")"
            ),
            calculator_label="external (operator-supplied)",
            samples_origin="external_samples",
            provenance=provenance,
        )


__all__ = ["ExternalSamplesBackend"]
